### ISSUE TITLE
Would it be possible to not put dependencies all in one line?

### ISSUE THREAD

**Issue by sh-at-cs** [zyf722/poetry-plugin-migrate#2]
When I ran and chose to migrate dependencies from `tool.poetry.dependencies` to `project.dependencies`, it put all of them in a single line, spanning 500+ characters.

Would it be possible to "pretty-print" options like this instead?

**Comment by jdrew82** [comment]
Agreed. It's much easier to read dependencies if they are one per line, especially if you're wanting to have comments for purpose behind each.

**Comment by zyf722** [comment]
Hi @sh-at-cs and @jdrew82,

This has been fixed in v0.2.1.

Generated main dependencies, optional dependencies, and dependency groups are now formatted with one entry per line. Comments attached to individual dependencies are also preserved where possible.

For example, given:

```toml
[tool.poetry]
name = "example-project"
version = "1.0.0"
description = "Dependency formatting example"
authors = []

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32" # HTTP client
httpx = "^0.28" # Async HTTP client
rich = { version = "^14.0", python = ">=3.10" } # Terminal output
```

after migration with [table ordering](https://github.com/zyf722/poetry-plugin-migrate#optional-table-order):

```toml
[project]
name = "example-project"
description = "Dependency formatting example"
version = "1.0.0"
authors = []
requires-python = '>=3.10,<4.0'
dependencies = [
  'requests>=2.32,<3.0', # HTTP client
  'httpx>=0.28,<0.29', # Async HTTP client
  'rich>=14.0,<15.0 ; python_version >= "3.10"', # Terminal output
]

[tool.poetry]

[tool.poetry.dependencies]
python = "^3.10"
```

Thanks for the suggestion!

*P.S. I also noticed the empty `[tool.poetry]` table left behind in the output. That'll be fixed in the next release as well.*
